# Generated by Django 5.0.3 on 2024-06-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="owned",
            field=models.BooleanField(default=False),
        ),
    ]
